version: '2'

services:
  db:
    image: wangxian/alpine-mysql
    restart: always
    environment:
      MYSQL_PORT: 3306
      MYSQL_DATABASE: CRM
      # So you don't have to use root, but you can if you like
      MYSQL_USER: admin
      # You can use whatever password you like
      MYSQL_PASSWORD: admin
      # Password for root access
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  django:
    build: ./server
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./server:/crm/server
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./client
    command: ["npm", "start"]
    volumes:
      - ./client:/crm/client
      - node-modules:/crm/client/node_modules
    ports:
      - "3000:3000"

volumes:
  my-db:
  node-modules: