# Generated by Django 2.2 on 2020-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_prochain_reglement', models.DateTimeField()),
                ('periodicite', models.CharField(choices=[('H', 'HEBDOMADAIRE'), ('M', 'MENSUEL'), ('T', 'TRIMESTRIEL'), ('S', 'SEMESTRIEL'), ('A', 'ANNUEL')], max_length=1)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mode_de_reglement', models.CharField(choices=[('P', 'PRELEVEMENT')], max_length=1)),
                ('statut', models.CharField(choices=[('R', 'REGLEMENT A JOUR'), ('N', 'NON A JOUR')], max_length=1)),
                ('statut_clieny', models.CharField(choices=[('A', 'ACTIF'), ('D', 'DESACTIVE')], max_length=1)),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('autorisation_prelevement', models.FileField(blank=True, null=True, upload_to='api/files/')),
            ],
        ),
    ]
