# Generated by Django 2.2 on 2020-04-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='date_prochain_reglement',
            new_name='date_reglement',
        ),
        migrations.RemoveField(
            model_name='client',
            name='statut_clieny',
        ),
        migrations.AddField(
            model_name='client',
            name='statut_client',
            field=models.CharField(choices=[('A', 'ACTIF'), ('D', 'DESACTIVE')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='mode_de_reglement',
            field=models.CharField(choices=[('P', 'PRELEVEMENT')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='periodicite',
            field=models.CharField(choices=[('H', 'HEBDOMADAIRE'), ('M', 'MENSUEL'), ('T', 'TRIMESTRIEL'), ('S', 'SEMESTRIEL'), ('A', 'ANNUEL')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('R', 'REGLEMENT A JOUR'), ('N', 'NON A JOUR')], default='N', max_length=1),
        ),
    ]
