# Generated by Django 2.2 on 2020-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200405_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='statut_client',
            field=models.CharField(choices=[('A', 'ACTIF'), ('D', 'DESACTIVE')], default='D', max_length=1),
        ),
    ]
