# Generated by Django 3.0.5 on 2020-04-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200410_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(default='uBth2wiDupUCGs4jvNlqEYFW7zHjtwPhnkBXDzZMZcA', max_length=255),
        ),
    ]
