# Generated by Django 3.0.5 on 2020-04-21 14:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_client_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='autorisation_prelevement',
            field=models.FileField(blank=True, null=True, upload_to=api.models.client_directory_path),
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(default='Kxu7E-eTLxC6IBCYtKHGwCuF3PJAzL0PRn1qyg58h5g', max_length=255),
        ),
    ]
