# Generated by Django 3.0.5 on 2020-04-21 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200421_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(default='U56e8sh80BAE5_3UcCLxdGojzygOjVvipc6AnsQd_OE', max_length=255),
        ),
    ]
