# Generated by Django 3.0.5 on 2020-04-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200421_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(default='irGDU5zAsGu7REosyTbdRtSR-AQ7ImLVhJ131lQmT44', max_length=255),
        ),
    ]
