# Generated by Django 3.0.5 on 2020-05-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200430_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(default='8fWgyq-a8uZwjbTH_IgFaTkj-zRaMvF6MJH8AckW8Cw', max_length=255),
        ),
    ]
