# Generated by Django 3.0.5 on 2020-05-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200501_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(default='LkoJolOhKsGnIQxHPMS1gz_iNnSv8-suM6tH4DHZ_zo', max_length=255),
        ),
    ]
