# Generated by Django 3.0.5 on 2020-05-02 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200501_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(default='CfGIpRLqIm_RH5QNxWsTpfrjtRHD8qmIePLe6rilAkk', max_length=255),
        ),
    ]
