# Generated by Django 3.0.5 on 2020-05-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200502_1035'),
        ('api', '0012_auto_20200502_0924'),
    ]

    operations = [
    ]
